# Generated by Django 5.1.7 on 2025-03-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('weight', models.FloatField(default=1.0, verbose_name='peso')),
                ('implementation_key', models.CharField(max_length=100, unique=True, verbose_name='clave de implementación')),
            ],
            options={
                'verbose_name': 'criterio de análisis',
                'verbose_name_plural': 'criterios de análisis',
            },
        ),
        migrations.CreateModel(
            name='DatasetArticleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credibility_score', models.FloatField(verbose_name='puntuación de credibilidad')),
                ('analysis_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de análisis')),
                ('summary', models.TextField(blank=True, verbose_name='resumen')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='dataset.newsarticle', verbose_name='artículo')),
            ],
            options={
                'verbose_name': 'análisis de artículo del dataset',
                'verbose_name_plural': 'análisis de artículos del dataset',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='CriterionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='puntuación')),
                ('explanation', models.TextField(verbose_name='explicación')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_results', to='analyzer.datasetarticleanalysis', verbose_name='criterio')),
            ],
            options={
                'verbose_name': 'resultado de criterio',
                'verbose_name_plural': 'resultados de criterios',
            },
        ),
    ]
