# Generated by Django 5.1.7 on 2025-03-19 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('content', models.TextField(verbose_name='contenido')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='autor')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='fuente')),
                ('credibility_score', models.FloatField(blank=True, null=True, verbose_name='puntuación de credibilidad')),
                ('analysis_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de análisis')),
                ('summary', models.TextField(blank=True, verbose_name='resumen')),
            ],
            options={
                'verbose_name': 'análisis de contenido',
                'verbose_name_plural': 'análisis de contenido',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('weight', models.FloatField(default=1.0, verbose_name='peso')),
                ('implementation_key', models.CharField(max_length=100, unique=True, verbose_name='clave de implementación')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'criterio de verificación',
                'verbose_name_plural': 'criterios de verificación',
            },
        ),
        migrations.CreateModel(
            name='CriterionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='puntuación')),
                ('explanation', models.TextField(verbose_name='explicación')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_results', to='analyzer.contentanalysis', verbose_name='análisis')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.verificationcriterion', verbose_name='criterio')),
            ],
            options={
                'verbose_name': 'resultado de criterio',
                'verbose_name_plural': 'resultados de criterios',
                'unique_together': {('analysis', 'criterion')},
            },
        ),
    ]
