# Generated by Django 5.1.7 on 2025-03-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('color', models.CharField(default='#CCCCCC', max_length=7, verbose_name='color')),
            ],
            options={
                'verbose_name': 'categoría de verificación',
                'verbose_name_plural': 'categorías de verificación',
            },
        ),
        migrations.CreateModel(
            name='FactCheckArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('url', models.URLField(unique=True, verbose_name='URL')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('claim', models.TextField(verbose_name='afirmación verificada')),
                ('claim_source', models.CharField(max_length=255, verbose_name='fuente de la afirmación')),
                ('content', models.TextField(verbose_name='contenido')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de la imagen')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='etiquetas')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='autor')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de extracción')),
                ('is_processed', models.BooleanField(default=False, verbose_name='procesado')),
                ('verification_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='scraper.verificationcategory', verbose_name='categoría de verificación')),
            ],
            options={
                'verbose_name': 'artículo de verificación',
                'verbose_name_plural': 'artículos de verificación',
                'ordering': ['-publish_date', '-scraped_at'],
            },
        ),
    ]
